name: Download Repo as Zip + Upload Artifact

on:
  workflow_dispatch:
    inputs:
      resumeUrl:
        description: 'N8N resume URL'
        required: true

jobs:
  download-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip entire repo
      run: zip -r repo.zip . -x "*.git*"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: repo-package
        path: repo.zip

    - name: Call N8N resume URL
      run: |
        curl -X POST ${{ inputs.resumeUrl }} \
          -H "Content-Type: application/json" \
          -d '{"message": "Build completed", "artifact": "repo-package"}'
