name: Download Repo as Zip + Upload Artifact

on:
  workflow_dispatch:
    inputs:
      resumeUrl:
        description: 'N8N resume URL'
        required: true
      artifact_name:
        description: 'Name of the artifact'
        required: true
        default: 'wp-autoboiler'

jobs:
  download-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare folder for zipping
        run: |
          mkdir ${{ github.event.inputs.artifact_name }}
          shopt -s dotglob
          for item in *; do
            if [ "$item" != "${{ github.event.inputs.artifact_name }}" ]; then
              cp -r "$item" "${{ github.event.inputs.artifact_name }}/"
            fi
          done

      - name: Zip theme folder (correct structure for WP)
        run: zip -r ${{ github.event.inputs.artifact_name }}.zip ${{ github.event.inputs.artifact_name }}

      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ github.event.inputs.artifact_name }}.zip

      # - name: Zip entire repo
      #   run: zip -r ${{ github.event.inputs.artifact_name }}.zip . -x "*.git*"

      # - name: Upload artifact
      #   id: upload
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build
      #     path: ${{ github.event.inputs.artifact_name }}.zip

      - name: Get artifact ID + output download URL
        id: set-output
        run: |
          artifact_id=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
            | jq '.artifacts[0].id')

          echo "artifact_zip_url=https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${artifact_id}/zip" >> $GITHUB_OUTPUT

      - name: Call N8N resume URL
        run: |
          curl -X POST "${{ inputs.resumeUrl }}" \
            -H "Content-Type: application/json" \
            -d "{\"message\": \"Build completed\", \"artifact_zip_url\": \"${{ steps.set-output.outputs.artifact_zip_url }}\"}"
