name: Download Repo as Zip + Upload Artifact

on:
  workflow_dispatch:
    types: [n8n-trigger]

jobs:
  download-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip entire repo
      run: |
        zip -r repo.zip . -x "*.git*" 

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: repo-package
        path: repo.zip
