name: Download Repo as Zip + Upload Artifact

on:
  workflow_dispatch:
    inputs:
      resumeUrl:
        description: 'N8N resume URL'
        required: true

jobs:
  download-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip entire repo
        run: zip -r repo.zip . -x "*.git*"

      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: repo-package
          path: repo.zip

      - name: Get artifact ID + output download curl
        id: set-output
        run: |
          artifact_id=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
            | jq '.artifacts[0].id')

          curl_command="curl -L -H \"Accept: application/vnd.github+json\" -H \"Authorization: Bearer <YOUR-TOKEN>\" -H \"X-GitHub-Api-Version: 2022-11-28\" https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${artifact_id}/zip"

          echo "curl_command=${curl_command}" >> $GITHUB_OUTPUT

      - name: Call N8N resume URL
        run: |
          curl -X POST "${{ inputs.resumeUrl }}" \
            -H "Content-Type: application/json" \
            -d "{\"message\": \"Build completed\", \"curl_command\": \"${{ steps.set-output.outputs.curl_command }}\"}"
