name: Build WordPress Theme Zip

on:
  workflow_dispatch:
    inputs:
      resumeUrl:
        description: 'N8N resume URL'
        required: true
      artifact_name:
        description: 'Name of the artifact (theme folder name)'
        required: true
        default: 'wp-autoboiler'

jobs:
  build-theme-zip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build WordPress-ready theme ZIP (single non-nested zip)
        run: |
          THEME="${{ github.event.inputs.artifact_name }}"
          # Clean up any previous work
          rm -rf "$THEME" "$THEME.zip"
          mkdir "$THEME"
          shopt -s dotglob
          for item in *; do
            if [[ "$item" != "$THEME" && "$item" != ".git" && "$item" != ".github" && "$item" != "*.yml" && "$item" != "*.yaml" ]]; then
              cp -r "$item" "$THEME/"
            fi
          done
          zip -r "$THEME.zip" "$THEME"

      - name: Upload zip artifact (WordPress install-ready)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.artifact_name }}-wordpress-theme-zip
          path: ${{ github.event.inputs.artifact_name }}.zip
          compression-level: 0

      - name: Get artifact ID + output download URL
        id: set-output
        run: |
          sleep 5
          artifact_id=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
            | jq -r --arg name "${{ github.event.inputs.artifact_name }}-wordpress-theme-zip" '.artifacts[] | select(.name == $name) | .id')
          echo "artifact_zip_url=https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${artifact_id}/zip" >> $GITHUB_OUTPUT

      - name: Call N8N resume URL
        run: |
          curl -X POST "${{ inputs.resumeUrl }}" \
            -H "Content-Type: application/json" \
            -d "{\"message\": \"Build completed\", \"artifact_zip_url\": \"${{ steps.set-output.outputs.artifact_zip_url }}\"}"