name: Download Repo as Zip + Upload Artifact

on:
  workflow_dispatch:
    inputs:
      resumeUrl:
        description: 'N8N resume URL'
        required: true
      artifact_name:
        description: 'Name of the artifact (theme folder name)'
        required: true
        default: 'wp-autoboiler'

jobs:
  download-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare theme folder
        run: |
          THEME_FOLDER="${{ github.event.inputs.artifact_name }}"
          rm -rf "$THEME_FOLDER"
          mkdir "$THEME_FOLDER"
          
          # Copy all repo files except .git, .github, workflow yaml files into theme folder
          shopt -s dotglob
          for item in *; do
            if [[ "$item" != "$THEME_FOLDER" && "$item" != ".git" && "$item" != ".github" && "$item" != "*.yml" && "$item" != "*.yaml" ]]; then
              cp -r "$item" "$THEME_FOLDER/"
            fi
          done

      - name: Create WordPress-ready theme ZIP
        run: |
          THEME_FOLDER="${{ github.event.inputs.artifact_name }}"
          zip -r "${THEME_FOLDER}.zip" "$THEME_FOLDER"

      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.artifact_name }}
          path: ${{ github.event.inputs.artifact_name }}.zip
          compression-level: 0

      - name: Get artifact ID + output download URL
        id: set-output
        run: |
          sleep 5
          artifact_id=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
            | jq -r --arg name "${{ github.event.inputs.artifact_name }}" '.artifacts[] | select(.name == $name) | .id')
          echo "artifact_zip_url=https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${artifact_id}/zip" >> $GITHUB_OUTPUT

      - name: Call N8N resume URL
        run: |
          curl -X POST "${{ inputs.resumeUrl }}" \
            -H "Content-Type: application/json" \
            -d "{\"message\": \"Build completed\", \"artifact_zip_url\": \"${{ steps.set-output.outputs.artifact_zip_url }}\"}"